// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRM393API.Models;

#nullable disable

namespace PRM393API.Migrations
{
    [DbContext(typeof(Prm393dbContext))]
    [Migration("20260612042933_AddPhoneNumberUniqueIndex")]
    partial class AddPhoneNumberUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PRM393API.Models.AcademicRank", b =>
                {
                    b.Property<int>("RankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RankId"));

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("MinScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("RankName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RankId");

                    b.ToTable("AcademicRanks");
                });

            modelBuilder.Entity("PRM393API.Models.AcademicYear", b =>
                {
                    b.Property<int>("AcademicYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcademicYearId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("YearName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AcademicYearId");

                    b.HasIndex(new[] { "YearName" }, "UQ_AcademicYears_YearName")
                        .IsUnique();

                    b.ToTable("AcademicYears");
                });

            modelBuilder.Entity("PRM393API.Models.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementId"));

                    b.Property<string>("AnnouncementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("normal");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("AuthorId");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_Ann_CreatedAt")
                        .IsDescending();

                    b.HasIndex(new[] { "AnnouncementType" }, "IX_Ann_Type");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("PRM393API.Models.AnnouncementTarget", b =>
                {
                    b.Property<int>("TargetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TargetId"));

                    b.Property<int>("AnnouncementId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.HasKey("TargetId");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("ClassId");

                    b.ToTable("AnnouncementTargets");
                });

            modelBuilder.Entity("PRM393API.Models.Assessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentId"));

                    b.Property<DateOnly>("AssessmentDate")
                        .HasColumnType("date");

                    b.Property<string>("AssessmentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("AssessmentTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(10.0m);

                    b.Property<int>("TeachingAssignmentId")
                        .HasColumnType("int");

                    b.HasKey("AssessmentId");

                    b.HasIndex("AssessmentTypeId");

                    b.HasIndex("TeachingAssignmentId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("PRM393API.Models.AssessmentType", b =>
                {
                    b.Property<int>("AssessmentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentTypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("AssessmentTypeId");

                    b.ToTable("AssessmentTypes");
                });

            modelBuilder.Entity("PRM393API.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TeachingAssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("AssignmentId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TeachingAssignmentId");

                    b.HasIndex(new[] { "DueDate" }, "IX_Assign_DueDate");

                    b.HasIndex(new[] { "IsDeleted" }, "IX_Assign_IsDeleted");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("PRM393API.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("RecordedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TimetableId")
                        .HasColumnType("int");

                    b.HasKey("AttendanceId");

                    b.HasIndex("RecordedBy");

                    b.HasIndex(new[] { "AttendanceDate" }, "IX_Att_Date");

                    b.HasIndex(new[] { "StudentId" }, "IX_Att_StudentId");

                    b.HasIndex(new[] { "TimetableId", "StudentId", "AttendanceDate" }, "UQ_AttendanceRecords")
                        .IsUnique();

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("PRM393API.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("HomeroomTeacherId")
                        .HasColumnType("int");

                    b.HasKey("ClassId");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("HomeroomTeacherId");

                    b.HasIndex(new[] { "ClassName", "AcademicYearId" }, "UQ_Classes_NameYear")
                        .IsUnique();

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("PRM393API.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DepartmentId");

                    b.HasIndex(new[] { "DepartmentName" }, "UQ_Departments_Name")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("PRM393API.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("EnteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("EnteredBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("GradeId");

                    b.HasIndex("EnteredBy");

                    b.HasIndex(new[] { "AssessmentId" }, "IX_Grades_AssessmentId");

                    b.HasIndex(new[] { "StudentId" }, "IX_Grades_StudentId");

                    b.HasIndex(new[] { "AssessmentId", "StudentId" }, "UQ_Grades")
                        .IsUnique();

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("PRM393API.Models.NotificationLog", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int?>("AnnouncementId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex(new[] { "UserId", "IsRead" }, "IX_NL_UserId_IsRead");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("PRM393API.Models.ParentStudent", b =>
                {
                    b.Property<int>("ParentStudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParentStudentId"));

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Phụ huynh");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("ParentStudentId");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "ParentId", "StudentId" }, "UQ_ParentStudents")
                        .IsUnique();

                    b.ToTable("ParentStudents");
                });

            modelBuilder.Entity("PRM393API.Models.RefreshToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TokenId");

                    b.HasIndex(new[] { "Token" }, "IX_RefreshTokens_Token");

                    b.HasIndex(new[] { "UserId" }, "IX_RefreshTokens_UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PRM393API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex(new[] { "RoleName" }, "UQ_Roles_RoleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PRM393API.Models.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterId"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("SemesterId");

                    b.HasIndex(new[] { "AcademicYearId", "SemesterName" }, "UQ_Semesters_Year_Name")
                        .IsUnique();

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("PRM393API.Models.StudentClass", b =>
                {
                    b.Property<int>("StudentClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentClassId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("StudentClassId");

                    b.HasIndex(new[] { "ClassId" }, "IX_SC_ClassId");

                    b.HasIndex(new[] { "StudentId" }, "IX_SC_StudentId");

                    b.HasIndex(new[] { "StudentId", "ClassId" }, "UQ_StudentClasses")
                        .IsUnique();

                    b.ToTable("StudentClasses");
                });

            modelBuilder.Entity("PRM393API.Models.StudentRequest", b =>
                {
                    b.Property<int>("StudentRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentRequestId"));

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateOnly>("LeaveDate")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("int");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("StudentRequestId");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex(new[] { "Status" }, "IX_SR_Status");

                    b.HasIndex(new[] { "StudentId" }, "IX_SR_StudentId");

                    b.ToTable("StudentRequests");
                });

            modelBuilder.Entity("PRM393API.Models.StudentSemesterSummary", b =>
                {
                    b.Property<int>("SummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SummaryId"));

                    b.Property<string>("Conduct")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EvaluatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("EvaluatedBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("Gpa")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("GPA");

                    b.Property<int?>("RankId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("SummaryId");

                    b.HasIndex("EvaluatedBy");

                    b.HasIndex("RankId");

                    b.HasIndex(new[] { "SemesterId" }, "IX_SSS_SemesterId");

                    b.HasIndex(new[] { "StudentId" }, "IX_SSS_StudentId");

                    b.HasIndex(new[] { "StudentId", "SemesterId" }, "UQ_StudentSemesterSummaries")
                        .IsUnique();

                    b.ToTable("StudentSemesterSummaries");
                });

            modelBuilder.Entity("PRM393API.Models.StudentYearlySummary", b =>
                {
                    b.Property<int>("YearlySummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YearlySummaryId"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EvaluatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("EvaluatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("RankId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("YearlyConduct")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("YearlyGpa")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("YearlyGPA");

                    b.HasKey("YearlySummaryId");

                    b.HasIndex("EvaluatedBy");

                    b.HasIndex("RankId");

                    b.HasIndex(new[] { "AcademicYearId" }, "IX_SYS_AcademicYearId");

                    b.HasIndex(new[] { "StudentId" }, "IX_SYS_StudentId");

                    b.HasIndex(new[] { "StudentId", "AcademicYearId" }, "UQ_StudentYearlySummaries")
                        .IsUnique();

                    b.ToTable("StudentYearlySummaries");
                });

            modelBuilder.Entity("PRM393API.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubjectId");

                    b.HasIndex(new[] { "SubjectCode" }, "UQ_Subjects_SubjectCode")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("PRM393API.Models.Submission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("ContentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feedback")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GradedBy")
                        .HasColumnType("int");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("SubmissionId");

                    b.HasIndex("GradedBy");

                    b.HasIndex(new[] { "AssignmentId" }, "IX_Sub_AssignmentId");

                    b.HasIndex(new[] { "StudentId" }, "IX_Sub_StudentId");

                    b.HasIndex(new[] { "AssignmentId", "StudentId" }, "UQ_Submissions")
                        .IsUnique();

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("PRM393API.Models.TeachingAssignment", b =>
                {
                    b.Property<int>("TeachingAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeachingAssignmentId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("TeachingAssignmentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex(new[] { "ClassId" }, "IX_TA_ClassId");

                    b.HasIndex(new[] { "SemesterId" }, "IX_TA_SemesterId");

                    b.HasIndex(new[] { "TeacherId" }, "IX_TA_TeacherId");

                    b.HasIndex(new[] { "TeacherId", "ClassId", "SubjectId", "SemesterId" }, "UQ_TeachingAssignments")
                        .IsUnique();

                    b.ToTable("TeachingAssignments");
                });

            modelBuilder.Entity("PRM393API.Models.Timetable", b =>
                {
                    b.Property<int>("TimetableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimetableId"));

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("RoomName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.Property<int>("TeachingAssignmentId")
                        .HasColumnType("int");

                    b.HasKey("TimetableId");

                    b.HasIndex("SlotId");

                    b.HasIndex("TeachingAssignmentId");

                    b.ToTable("Timetables");
                });

            modelBuilder.Entity("PRM393API.Models.TimetableSlot", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotId"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("SlotId");

                    b.ToTable("TimetableSlots");
                });

            modelBuilder.Entity("PRM393API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex(new[] { "RoleId" }, "IX_Users_RoleId");

                    b.HasIndex(new[] { "Username" }, "IX_Users_Username");

                    b.HasIndex(new[] { "PhoneNumber" }, "UQ_Users_PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.HasIndex(new[] { "Username" }, "UQ_Users_Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PRM393API.Models.Announcement", b =>
                {
                    b.HasOne("PRM393API.Models.User", "Author")
                        .WithMany("Announcements")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK_Ann_Author");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("PRM393API.Models.AnnouncementTarget", b =>
                {
                    b.HasOne("PRM393API.Models.Announcement", "Announcement")
                        .WithMany("AnnouncementTargets")
                        .HasForeignKey("AnnouncementId")
                        .IsRequired()
                        .HasConstraintName("FK_AT_Announcements");

                    b.HasOne("PRM393API.Models.Class", "Class")
                        .WithMany("AnnouncementTargets")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_AT_Classes");

                    b.Navigation("Announcement");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("PRM393API.Models.Assessment", b =>
                {
                    b.HasOne("PRM393API.Models.AssessmentType", "AssessmentType")
                        .WithMany("Assessments")
                        .HasForeignKey("AssessmentTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Assess_Type");

                    b.HasOne("PRM393API.Models.TeachingAssignment", "TeachingAssignment")
                        .WithMany("Assessments")
                        .HasForeignKey("TeachingAssignmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Assess_TA");

                    b.Navigation("AssessmentType");

                    b.Navigation("TeachingAssignment");
                });

            modelBuilder.Entity("PRM393API.Models.Assignment", b =>
                {
                    b.HasOne("PRM393API.Models.User", "CreatedByNavigation")
                        .WithMany("Assignments")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Assign_CreatedBy");

                    b.HasOne("PRM393API.Models.TeachingAssignment", "TeachingAssignment")
                        .WithMany("Assignments")
                        .HasForeignKey("TeachingAssignmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Assign_TA");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("TeachingAssignment");
                });

            modelBuilder.Entity("PRM393API.Models.AttendanceRecord", b =>
                {
                    b.HasOne("PRM393API.Models.User", "RecordedByNavigation")
                        .WithMany("AttendanceRecordRecordedByNavigations")
                        .HasForeignKey("RecordedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Att_RecordedBy");

                    b.HasOne("PRM393API.Models.User", "Student")
                        .WithMany("AttendanceRecordStudents")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Att_Students");

                    b.HasOne("PRM393API.Models.Timetable", "Timetable")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("TimetableId")
                        .IsRequired()
                        .HasConstraintName("FK_Att_Timetable");

                    b.Navigation("RecordedByNavigation");

                    b.Navigation("Student");

                    b.Navigation("Timetable");
                });

            modelBuilder.Entity("PRM393API.Models.Class", b =>
                {
                    b.HasOne("PRM393API.Models.AcademicYear", "AcademicYear")
                        .WithMany("Classes")
                        .HasForeignKey("AcademicYearId")
                        .IsRequired()
                        .HasConstraintName("FK_Classes_AcademicYears");

                    b.HasOne("PRM393API.Models.User", "HomeroomTeacher")
                        .WithMany("Classes")
                        .HasForeignKey("HomeroomTeacherId")
                        .HasConstraintName("FK_Classes_HomeroomTeacher");

                    b.Navigation("AcademicYear");

                    b.Navigation("HomeroomTeacher");
                });

            modelBuilder.Entity("PRM393API.Models.Grade", b =>
                {
                    b.HasOne("PRM393API.Models.Assessment", "Assessment")
                        .WithMany("Grades")
                        .HasForeignKey("AssessmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Grades_Assessments");

                    b.HasOne("PRM393API.Models.User", "EnteredByNavigation")
                        .WithMany("GradeEnteredByNavigations")
                        .HasForeignKey("EnteredBy")
                        .IsRequired()
                        .HasConstraintName("FK_Grades_EnteredBy");

                    b.HasOne("PRM393API.Models.User", "Student")
                        .WithMany("GradeStudents")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Grades_Students");

                    b.Navigation("Assessment");

                    b.Navigation("EnteredByNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PRM393API.Models.NotificationLog", b =>
                {
                    b.HasOne("PRM393API.Models.Announcement", "Announcement")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("AnnouncementId")
                        .HasConstraintName("FK_NL_Announcements");

                    b.HasOne("PRM393API.Models.User", "User")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_NL_Users");

                    b.Navigation("Announcement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRM393API.Models.ParentStudent", b =>
                {
                    b.HasOne("PRM393API.Models.User", "Parent")
                        .WithMany("ParentStudentParents")
                        .HasForeignKey("ParentId")
                        .IsRequired()
                        .HasConstraintName("FK_PS_Parents");

                    b.HasOne("PRM393API.Models.User", "Student")
                        .WithMany("ParentStudentStudents")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_PS_Students");

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PRM393API.Models.RefreshToken", b =>
                {
                    b.HasOne("PRM393API.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRM393API.Models.Semester", b =>
                {
                    b.HasOne("PRM393API.Models.AcademicYear", "AcademicYear")
                        .WithMany("Semesters")
                        .HasForeignKey("AcademicYearId")
                        .IsRequired()
                        .HasConstraintName("FK_Semesters_AcademicYears");

                    b.Navigation("AcademicYear");
                });

            modelBuilder.Entity("PRM393API.Models.StudentClass", b =>
                {
                    b.HasOne("PRM393API.Models.Class", "Class")
                        .WithMany("StudentClasses")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_SC_Classes");

                    b.HasOne("PRM393API.Models.User", "Student")
                        .WithMany("StudentClasses")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_SC_Students");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PRM393API.Models.StudentRequest", b =>
                {
                    b.HasOne("PRM393API.Models.User", "RequestedByNavigation")
                        .WithMany("StudentRequestRequestedByNavigations")
                        .HasForeignKey("RequestedBy")
                        .IsRequired()
                        .HasConstraintName("FK_SR_RequestedBy");

                    b.HasOne("PRM393API.Models.User", "ReviewedByNavigation")
                        .WithMany("StudentRequestReviewedByNavigations")
                        .HasForeignKey("ReviewedBy")
                        .HasConstraintName("FK_SR_ReviewedBy");

                    b.HasOne("PRM393API.Models.User", "Student")
                        .WithMany("StudentRequestStudents")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_SR_Students");

                    b.Navigation("RequestedByNavigation");

                    b.Navigation("ReviewedByNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PRM393API.Models.StudentSemesterSummary", b =>
                {
                    b.HasOne("PRM393API.Models.User", "EvaluatedByNavigation")
                        .WithMany("StudentSemesterSummaryEvaluatedByNavigations")
                        .HasForeignKey("EvaluatedBy")
                        .HasConstraintName("FK_SSS_EvaluatedBy");

                    b.HasOne("PRM393API.Models.AcademicRank", "Rank")
                        .WithMany("StudentSemesterSummaries")
                        .HasForeignKey("RankId")
                        .HasConstraintName("FK_SSS_Ranks");

                    b.HasOne("PRM393API.Models.Semester", "Semester")
                        .WithMany("StudentSemesterSummaries")
                        .HasForeignKey("SemesterId")
                        .IsRequired()
                        .HasConstraintName("FK_SSS_Semesters");

                    b.HasOne("PRM393API.Models.User", "Student")
                        .WithMany("StudentSemesterSummaryStudents")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_SSS_Students");

                    b.Navigation("EvaluatedByNavigation");

                    b.Navigation("Rank");

                    b.Navigation("Semester");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PRM393API.Models.StudentYearlySummary", b =>
                {
                    b.HasOne("PRM393API.Models.AcademicYear", "AcademicYear")
                        .WithMany("StudentYearlySummaries")
                        .HasForeignKey("AcademicYearId")
                        .IsRequired()
                        .HasConstraintName("FK_SYS_AcademicYears");

                    b.HasOne("PRM393API.Models.User", "EvaluatedByNavigation")
                        .WithMany("StudentYearlySummaryEvaluatedByNavigations")
                        .HasForeignKey("EvaluatedBy")
                        .HasConstraintName("FK_SYS_EvaluatedBy");

                    b.HasOne("PRM393API.Models.AcademicRank", "Rank")
                        .WithMany("StudentYearlySummaries")
                        .HasForeignKey("RankId")
                        .HasConstraintName("FK_SYS_Ranks");

                    b.HasOne("PRM393API.Models.User", "Student")
                        .WithMany("StudentYearlySummaryStudents")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_SYS_Students");

                    b.Navigation("AcademicYear");

                    b.Navigation("EvaluatedByNavigation");

                    b.Navigation("Rank");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PRM393API.Models.Submission", b =>
                {
                    b.HasOne("PRM393API.Models.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Sub_Assignments");

                    b.HasOne("PRM393API.Models.User", "GradedByNavigation")
                        .WithMany("SubmissionGradedByNavigations")
                        .HasForeignKey("GradedBy")
                        .HasConstraintName("FK_Sub_GradedBy");

                    b.HasOne("PRM393API.Models.User", "Student")
                        .WithMany("SubmissionStudents")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Sub_Students");

                    b.Navigation("Assignment");

                    b.Navigation("GradedByNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PRM393API.Models.TeachingAssignment", b =>
                {
                    b.HasOne("PRM393API.Models.Class", "Class")
                        .WithMany("TeachingAssignments")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_TA_Classes");

                    b.HasOne("PRM393API.Models.Semester", "Semester")
                        .WithMany("TeachingAssignments")
                        .HasForeignKey("SemesterId")
                        .IsRequired()
                        .HasConstraintName("FK_TA_Semesters");

                    b.HasOne("PRM393API.Models.Subject", "Subject")
                        .WithMany("TeachingAssignments")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_TA_Subjects");

                    b.HasOne("PRM393API.Models.User", "Teacher")
                        .WithMany("TeachingAssignments")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_TA_Teachers");

                    b.Navigation("Class");

                    b.Navigation("Semester");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("PRM393API.Models.Timetable", b =>
                {
                    b.HasOne("PRM393API.Models.TimetableSlot", "Slot")
                        .WithMany("Timetables")
                        .HasForeignKey("SlotId")
                        .IsRequired()
                        .HasConstraintName("FK_Timetables_Slots");

                    b.HasOne("PRM393API.Models.TeachingAssignment", "TeachingAssignment")
                        .WithMany("Timetables")
                        .HasForeignKey("TeachingAssignmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Timetables_TA");

                    b.Navigation("Slot");

                    b.Navigation("TeachingAssignment");
                });

            modelBuilder.Entity("PRM393API.Models.User", b =>
                {
                    b.HasOne("PRM393API.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK_Users_Departments");

                    b.HasOne("PRM393API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PRM393API.Models.AcademicRank", b =>
                {
                    b.Navigation("StudentSemesterSummaries");

                    b.Navigation("StudentYearlySummaries");
                });

            modelBuilder.Entity("PRM393API.Models.AcademicYear", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Semesters");

                    b.Navigation("StudentYearlySummaries");
                });

            modelBuilder.Entity("PRM393API.Models.Announcement", b =>
                {
                    b.Navigation("AnnouncementTargets");

                    b.Navigation("NotificationLogs");
                });

            modelBuilder.Entity("PRM393API.Models.Assessment", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("PRM393API.Models.AssessmentType", b =>
                {
                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("PRM393API.Models.Assignment", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("PRM393API.Models.Class", b =>
                {
                    b.Navigation("AnnouncementTargets");

                    b.Navigation("StudentClasses");

                    b.Navigation("TeachingAssignments");
                });

            modelBuilder.Entity("PRM393API.Models.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PRM393API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PRM393API.Models.Semester", b =>
                {
                    b.Navigation("StudentSemesterSummaries");

                    b.Navigation("TeachingAssignments");
                });

            modelBuilder.Entity("PRM393API.Models.Subject", b =>
                {
                    b.Navigation("TeachingAssignments");
                });

            modelBuilder.Entity("PRM393API.Models.TeachingAssignment", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Assignments");

                    b.Navigation("Timetables");
                });

            modelBuilder.Entity("PRM393API.Models.Timetable", b =>
                {
                    b.Navigation("AttendanceRecords");
                });

            modelBuilder.Entity("PRM393API.Models.TimetableSlot", b =>
                {
                    b.Navigation("Timetables");
                });

            modelBuilder.Entity("PRM393API.Models.User", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Assignments");

                    b.Navigation("AttendanceRecordRecordedByNavigations");

                    b.Navigation("AttendanceRecordStudents");

                    b.Navigation("Classes");

                    b.Navigation("GradeEnteredByNavigations");

                    b.Navigation("GradeStudents");

                    b.Navigation("NotificationLogs");

                    b.Navigation("ParentStudentParents");

                    b.Navigation("ParentStudentStudents");

                    b.Navigation("RefreshTokens");

                    b.Navigation("StudentClasses");

                    b.Navigation("StudentRequestRequestedByNavigations");

                    b.Navigation("StudentRequestReviewedByNavigations");

                    b.Navigation("StudentRequestStudents");

                    b.Navigation("StudentSemesterSummaryEvaluatedByNavigations");

                    b.Navigation("StudentSemesterSummaryStudents");

                    b.Navigation("StudentYearlySummaryEvaluatedByNavigations");

                    b.Navigation("StudentYearlySummaryStudents");

                    b.Navigation("SubmissionGradedByNavigations");

                    b.Navigation("SubmissionStudents");

                    b.Navigation("TeachingAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
