// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PRM393API.Models;

#nullable disable

namespace PRM393API.Migrations
{
    [DbContext(typeof(Prm393dbContext))]
    [Migration("20260717090000_AddPasswordResetAndUniqueEmail")]
    partial class AddPasswordResetAndUniqueEmail
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");
#pragma warning restore 612, 618
        }
    }
}
